AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30
  CountComments: false

Metrics/AbcSize:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
